#ifndef CA_H_SENTRY
#define CA_H_SENTRY

/* Cellular automoton */
struct cellaton {
	int n_cells;             /* The number of cells (length of a line) */
	int n_gens;              /* The number of generations (lentgh of a collumn) */
	int idx_last_bit;        /* The last 7-th bit since it is 8 bit rule */
	int rule;                /* Rule in a decimal form */
	int bin_rule[8];         /* A sequence of binary digits of the rule */
	char *initgen;           /* The first generation */
	char *nextgen;           /* Generated by the rule on initgen */
	int rule_table[2][2][2]; /* [prev][cur][next] cell */
	char on;
	char off;
};

/* Start generating a cellular automoton */
void start_ca(struct cellaton *ca);

#endif
